name: vercel-deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Testing the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Run tests
        run: npm test
